 # Cloud Build config to build and deploy bloocube-backend to Cloud Run

steps:
  # Build the Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t", "asia-southeast1-docker.pkg.dev/$PROJECT_ID/bloocube/bloocube-backend:latest",
        "-f", "Bloocube-backend/Dockerfile",
        "Bloocube-backend"
      ]

  # Push the image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args: ["push", "asia-southeast1-docker.pkg.dev/$PROJECT_ID/bloocube/bloocube-backend:latest"]

  # Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "bloocube-backend",
        "--image", "asia-southeast1-docker.pkg.dev/$PROJECT_ID/bloocube/bloocube-backend:latest",
        "--region", "asia-southeast1",
        "--platform", "managed",
        "--allow-unauthenticated",
        "--port", "5000",
        "--memory", "1Gi",
        "--cpu", "1",
        "--timeout", "300",
        "--set-env-vars", "NODE_ENV=production,CORS_ORIGIN=http://localhost:3000,https://bloocube.com,https://admin.bloocube.com,https://api-backend.bloocube.com,https://api-ai-services.bloocube.com"
      ]

images:
  - asia-southeast1-docker.pkg.dev/$PROJECT_ID/bloocube/bloocube-backend:latest

options:
  logging: CLOUD_LOGGING_ONLY
